### ISSUE TITLE
Heavy avatars returns a 500 error

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2299]
The avatar on [this page](https://opencollective.com/lajacqueline/pay/details) is not displayed. The server returns a 500 error for https://images.opencollective.com/lajacqueline/logo.png.

The logs say:
```
error: logo: error processing https://opencollective-production.s3-us-west-1.amazonaws.com/9140f6c0-0f0f-11e8-bedc-5dca82356013.jpg (VipsJpeg: Invalid SOS parameters for sequential JPEG 
VipsJpeg: out of order read at line 0 
vips2png: unable to write to buffer 
) 
```

A possible explanation is that https://opencollective-production.s3-us-west-1.amazonaws.com/9140f6c0-0f0f-11e8-bedc-5dca82356013.jpg is pretty heavy, it's more than 6mo.

## Solution 

Send a default image if an exception occurs when trying to process the image

**Comment by znarf** [comment]
Agree, we should have a maximum width/height, and perhaps a lower size too. A default image instead of an error would be also great.

**Comment by maddhruv** [comment]
> Send a default image if an exception occurs when trying to process the image

-1

'cause an error is an error - by throwing some sort of error (`Error processing large image`) or just the Internal Server Error reflects that something is wrong with either the server or the image itself

while sending a default image seems to be more like a mistake
that either the server or the user has done something wrong

**Comment by maddhruv** [comment]
This solution seems to be more viable
 - Limit avatar upload size (memory (mb) or dimensions)
 - and compress/resize the image on upload

**Comment by Betree** [comment]
> Send a default image if an exception occurs when trying to process the image
> 
> -1
> 
> 'cause an error is an error - by throwing some sort of error (`Error processing large image`) or just the Internal Server Error reflects that something is wrong with either the server or the image itself
> 
> while sending a default image seems to be more like a mistake
> that either the server or the user has done something wrong
> 
> It is almost as similar to as - sending a default user when a user is not found
> 
> instead, on the UI itslef we can show some default image or `error` image which would simply mean - a different image with a message

Our images service already generates default images when users haven't uploaded one:

![image](https://user-images.githubusercontent.com/1556356/65861487-a4a8a680-e36c-11e9-9c1a-493dfbb92e5d.png)

We prefer to handle this at the images service level rather than in the UI because then we will have to update multiple services (for example our invoices service or the widgets are supposed to fetch users images from there too). It is not the responsibility of frontend to handle these errors, if third parties use our API to build their own interfaces they shouldn't have to deal with such errors. With a good reporting system, we're notified not because things are broken on the client side but because we get an automatic message :slightly_smiling_face: 

> This solution seems to be more viable
> - Limit avatar upload size (memory (mb) or dimensions)
> - and compress/resize the image on upload

This is what's proposed above, the three solutions make sense and are not exclusive.

**Comment by Betree** [comment]
@NotJohs any update on this one? Can we help?

**Comment by NotJohs** [comment]
@Betree Yes. I have everything in place to do the validation but the only problem is notification.

**Comment by Betree** [comment]
@NotJohs It's fine to throw an error. Message needs to be explicit, for example:

> Image resolution needs to be less than 3000x3000, and file size must be below 5mo.

**Comment by NotJohs** [comment]
@Betree Alright

**Comment by znarf** [comment]
@Betree I merged the frontend PR, do you still want to add an API PR?

**Comment by znarf** [comment]
🏆 This issue was completed by @NotJohs as part as our first Hackathon (it started at at the event but was finished after). 

I retroactively added a $300 bounty on it (it's an old issue, so based on our previous complexity classification, it might have been a "minimal" in today's one). 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new

**Comment by znarf** [comment]
@Betree Closing this one for now out of clarity. Please open a new one if you want to follow up.

**Comment by Betree** [comment]
The issue reported here is not solved, https://images.opencollective.com/lajacqueline/logo.png still returns a 500 error and none of the three proposed outcomes (or equivalent solutions) were implemented in a systemic way (on the API).

I've updated the scope of this issue to limit the fix to what will solve the problem reported here:
- Send a default image if an exception occurs when trying to process the image

**Comment by znarf** [comment]
@Betree See my last comment https://github.com/opencollective/opencollective/issues/2299#issuecomment-551023330 We unfortunately acknowledged the issue went off track, this is why I want to start again from a clean state.

**Comment by Betree** [comment]
Will follow up in https://github.com/opencollective/opencollective/issues/2627

**Comment by NotJohs** [comment]
> * Send a default image if an exception occurs when trying to process the image

It meets this particular requirement. The default image is loaded when upload fails but this is done client-side.

**Comment by Betree** [comment]
> > * Send a default image if an exception occurs when trying to process the image
> 
> It meets this particular requirement. The default image is loaded when upload fails but this is done client-side.

@NotJohs it doesn't, https://images.opencollective.com/lajacqueline/logo.png returns a 500 error - not a default image. You can see on this page that it shows a broken image https://opencollective.com/lajacqueline:

![image](https://user-images.githubusercontent.com/1556356/68759782-a96da500-0610-11ea-85f0-ead9c95bea01.png)

**Comment by NotJohs** [comment]
@Betree I think I understand what you mean.
Since am handling this issue client-side it was specific to heroAvatar but not other areas.
So you need a client-side implementation that would check the image size and if it's too large would return a default image with an error message.

Please confirm if this is the direction of solution to this issue?

**Comment by Betree** [comment]
@NotJohs There's no client side code to do for this issue, what we need is to return the default image when it crashed in the image service https://github.com/opencollective/opencollective-images

Limiting the max upload size more aggressively would also be nice, but we must first implement it on the API side. A client limitation that works for all image upload (hero avatar, banner, expense attachements...etc) would be nice, but it's nor a priority.

**Comment by NotJohs** [comment]
@Betree Understood.
