### ISSUE TITLE
[PROJECT] Host Dashboard Revamp 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2896]
## Purpose
This project's goal is to improve the experience of hosts on the platform by re-designing the dashboard. We prioritized this because it's aligned with the new business model of plans for hosts. 

There are other improvements to be done for hosts, they are listed here but they are outside of the scope of this project. Full document [here](https://docs.google.com/document/d/1IedBuFfFCGO9H4FGNf-cDpp4FLm8J9PM7fxxFGxerT8/)

## Owner
@piamancini 
Design owner @Memo-Es 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Does this serve our mission?
Yes, it enables fiscal hosts to better manage their finances for their communities. 

- Will this help to make us financially sustainable within a year?
Yes, by improving the experience we aim to attract more hosts on the platform. 

- Is it feasible to build and maintain with our team and runway?
The scope of this project is to re-design. 

- Can this make us move faster?
Hopefully it'll make it less buggy and more intuitive. Lowering both the support time and the many requests for mall improvements.  

- Does this increase quality and not technical debt?
yes. 

- Will this bring us more Collective and financial contributors?
It aims at brining more hosts. 

- Is this already solved elsewhere or is it our unique contribution?
Unique. 

## Roadmap & Timeframe
(Key milestones or phases and estimated delivery dates, including specs, design, feature development, feedback, marketing/comms, and documentation)

**Specs** below
**Design Delivery**: April 
**Implementation**: Q2

### Expense Actions
_As a host Admin I want to be able to_

- Mark an expense as paid 
- Mark an expense as unpaid (#2773)
- Pay an expense with PayPal
- Pay an expense with Transferwise
- Pay expense with payment method Other
- Reject and Expense 
- Approve an expense
- Un-approve an expense 
- Delete and expense
- Edit an expense (incl. paypal and transferwise details)
- See expense status / narrative
- Add funds on a particular tier (for example, I want to add funds from someone who is a platinum sponsors)
- Edit an added funds transaction

### Search and Sort
- Filter by payout type (paypal, manual, transferwise)
- Search expenses and pending orders by 
date, 
status, 
collective, 
user, 
type, 
tax form
ID number
amount
Search/sort Collectives:
display and search/sort collective list
balance, 
date of last activity
fee

### Fees Actions 
- As a host Admin I want to manage the different fees I charge per collective. (#2821)

### Reports & Data Export
- As a host admin I want to have access to the archive of host reports. (#2798)

- As a host admin, I want to be able to export data about my host. (#2808)
 All transactions across all collectives
Collectives information 
Collective name
Collective slug
Approved date
Collective admins name and email addresses 
Collective balance
Annual Budget
Number of Financial contributors 
Active / Archived Status
Financial Contributors Info
List of Financial Contributors across collectives 
Email addresses 
Billing address 
Accumulated amount donated

### Bank Transfers (Pending Orders)

- As a host admin I want to manage my pending orders (manual donations that need to be confirmed, for example bank transfers) from my host dashboard. 
- I want to edit the amount received (or include a box for payment processor fees) (#2702)
- I want to send a company an invoice in advance to create and create a pending order for ir (#2456)
- Search and filter per date, collective, id, amount

### Email Service & Community Engagement
- As a host admin I want to send an update to collective admins and financial contributors across my collective. Enable Updates for Hosts (#2314)
- As a host admin I want to edit the thank you / receipt emails that get sent automatically to financial contributors.

### Pending Applications 
- Show detailed Collective info and responses to application questions in pending applications tab on dashboard

## Success metrics
(What we will judge outcomes of the project by)
Number of hosts on the platform on a paid plan

**Comment by alanna** [comment]
To discuss: plan for talking to hosts and potential hosts to get customer feedback before finalising and prioritising project specs.

**Comment by piamancini** [comment]
@alanna Yes - I already posted it in all hosts channels on Slack. I'm not sure I would do a specific communication about this, we can bundle it with other information - Include it in the next newsletter. Any ideas in particular?

**Comment by xdamman** [comment]
Should also be able to search expenses/pending orders by their ID number (as it is what is communicated as part of the wire transfer)

I’d also love to see the first page of the host dashboard to show the different items that require the host’s attention, i.e. expenses ready to be paid, pending orders that need to be marked as paid (moving the latter to a different tab has been a regression for that as there is now two places to check every time the host checks the dashboard). This page could also show a feed of the latest updates across all the hosted collectives.

It would also be interesting to have a way to see the list of inactive collectives with an easy way to reach out to them. This will help hosts keep their community of collective admins alive.

**Comment by jfdh** [comment]
Not sure if this the right place to put this, but I'd love to be able to use structured communication +++.../.../...+++ for incoming payements so that we dont have to mark financial contributions as paid. 

In relation to expense payement, and when people select "Other" instead of "Paypal" to get reimbursed, it would be nice to have a third option such as select "IBAN" and then force people to insert their first name, last name, IBAN, and communication desired.

**Comment by piamancini** [comment]
Thank you @jfdh !

> it would be nice to have a third option such as select "IBAN" and then force people to insert their first name, last name, IBAN, and communication desired.

This will happen, it's part of the expense flow re-design being implemented now. 

> structured communication +++.../.../...+++ for incoming payements so that we dont have to mark financial contributions as paid.

Can you explain this further?

**Comment by jfdh** [comment]
> > structured communication +++.../.../...+++ for incoming payements so that we dont have to mark financial contributions as paid.
> 
> Can you explain this further?

Sure. For now, when people people choose to make a donation through bank transfer / virement bancaire on Open Collective, they receive an email "Action required". On this email, we are asking them to write a communication of this type: xr-belgium order 64329. This is nice because I can link the code 64329 from the bank account to what appears on my dashboard (but I need to check this for each payement and manually mark as paid).

That is why it would be even nicer if instead of asking them "xr-belgium order 64329", there was a code (structured communication +++.../.../...+++) in the email that sends a payement instruction to my bank account and to open collective so that open collective knows that this code was received on my bank account, and thus paid. A lot of services use this, see also https://help.ticketmaster.be/hc/en-us/articles/360007609313-Why-do-you-need-to-use-a-structured-communication-

I also attached an invoice which is asking me to write a structured communication when doing the payement (so that Smart doesn't have to manually check if all the clients pay their invoices).

Let me know if I can help.

[Facture 2020.PFV.011885.pdf](https://github.com/opencollective/opencollective/files/4186184/Facture.2020.PFV.011885.pdf)

**Comment by elijahv** [comment]
Want a section for managing collectives, both approved and pending.

I have several groups with a "pending" status that are in limbo. They're on my collective and I don't have a way to remove them.

**Comment by piamancini** [comment]
hi @elijahv you should see a pending applications tab on your host dashboard where you can reject expenses. We definitely need to improve usability here. 

<img width="1169" alt="Screen Shot 2020-02-12 at 12 03 56 PM" src="https://user-images.githubusercontent.com/3671070/74329283-cd679080-4d8f-11ea-93d1-321026a2636a.png">

A different matter is that pending collectives should not show on your host (cc @Betree I think we fixed this already?

**Comment by piamancini** [comment]
@jfdh thank you! This is super useful

**Comment by Betree** [comment]
> A different matter is that pending collectives should not show on your host (cc @Betree I think we fixed this already?

@piamancini they should not show indeed, we had this issue at some point but it has been fixed a while ago. If they are still showing then that's a new bug.

**Comment by Memo-Es** [comment]
### First design wireframes → Overarching structure

| Section | Image | Description |
| ------------- | ------------- | ------------- |
| Primary Navigation  | ![Primary navigation](https://user-images.githubusercontent.com/49539954/77284023-54fbc580-6c93-11ea-80c9-e61c9d45d6db.png) | Where you see the main sections that conforms the dashboard: Priority (Home), Expenses, Collectives and Contributions
| Secondary Navigation  | ![Secondary navigation](https://user-images.githubusercontent.com/49539954/77284022-54632f00-6c93-11ea-9361-0503a210138f.png)  |  Each of the main sections will have a contextual nav bar with different sub-sections 
| Global info  | ![Global info](https://user-images.githubusercontent.com/49539954/77284017-53320200-6c93-11ea-80ad-3d2c3f968807.png)  |  Here hosts will have important global info always at hand
| Host Profile and Settings | ![Host profile and settings](https://user-images.githubusercontent.com/49539954/77284018-53ca9880-6c93-11ea-8631-0e9dc0f094a0.png) |  Host info and link to settings page
| Action space | ![Action space](https://user-images.githubusercontent.com/49539954/77284013-50cfa800-6c93-11ea-8b34-5bc4f51b068b.png) | The space where hosts will interact with all the elements and perform tasks

I'll be uploading the definition of each section in the next days...

**Comment by flaki** [comment]
We are a [brand new host](https://opencollective.com/bayareatechclub) from Estonia so we only have limited hands-on experience with the interface, but we have been evaluating OC for some time so some feedback that might be worth having find its way into the new version.

### Expense details are inconsistent across UI
![Screenshot_2020-03-24 Rust Tallinn - Open Collective](https://user-images.githubusercontent.com/2089432/77459126-85f90900-6dff-11ea-9e5c-58707037f1d7.png)
Above: excerpt from a hosted collective, below: host dashboard (same transaction)
![Screenshot_2020-03-24 MTÜ Bay Area Tech Club - Open Collective](https://user-images.githubusercontent.com/2089432/77459140-8b565380-6dff-11ea-822d-de0df916979f.png)

The information displayed differently in the views, and in some cases even missing details (the charged host/payment fees is the most annoying here). We understand that privacy consideration might be at play in these interfaces (as some are also shown to the public), but interestingly the one that's missing the detailed information on fees (below) is from the *dashboard*.

As mentioned above, more consideration towards management of fees would be much welcome.

### First-class treatment for off-site financial transactions
Again, a theme mentioned above multiple times. As an Estonian host most often interacting with entities inside the EEA/EMU (eurozone), our primary interaction with these entities will be via our bank, and mostly in Euros. Wire transfers within SEPA are provided free-of-charge so this is our preferred method of reimbursements, invoice and other expense payments. Facilitating this with workflows that actively enable and make these transactions easier to execute and less hassle to deal with inside OC would be highly preferred. Relatedly:

### Need better UI discoverability (aka "finding Add Funds")
I've spent long minutes staring at the dashboard, clicking around in vain trying to find the way to add external funds received by the host to show up in OC. Then I spent a few hours carefully reading through the docs (I know, RTFM, I should have started there) until I finally found out that I needed to click into the search box on the dashboard, select a collective and only THEN this button will show up. Hopefully this will be fixed in the new edition, but hopefully discoverability of functions will be a prime factor in the new refactor as I consider myself a technically adept person, but I'd assume the dashboard would be used by many more folks with much less technological experience.

---

Regarding the wireframes shared @Memo-Es above for now these look promising. One question here: if the secondary navigation contains "sub-sections" of the primary navigation, what is the reasoning behind moving these to the top of the action area instead of the (perhaps more common) inlining in the rectangle of the primary navigation (and showing/hiding upon selection of primary element, a la accordion boxes)?

---

Hope this helps! In general we are really psyched about the upcoming host dashboard changes as we have high hopes for using OC and the affordances it will provide us to more efficiently cater for our collectives! :sparkling_heart:

**Comment by Memo-Es** [comment]
Hello @flaki !! 👋🏼

Thank you very much for taking the time to test the platform and write such an insightful review, this is super useful and much appreciated! 

* Totally agree with the feature discoverability, it is in fact one of the priorities of this project
* Will definitely take into account your suggestion on the navigation of the dashboard, will be sharing further wireframes in this issue, stay tuned! 

Thanks again and I hope your experience using Open Collective helps you connect and better maintain your community!

**Comment by Memo-Es** [comment]
### Update → Expenses (Wireframes)
In this screencap is showed the following features and user experience regarding expense management for fiscal host admins:


| Main actions  | Filter and search |
| ------------- | ------------- |
| <ul><li>Pay expenses</li><li>Mark an expense as paid / unpaid </li><li>Pay an expense with PayPal </li><li>Mark an expense as paid / unpaid </li><li>Add fees when paying </li><li>Change expense status (Reject / Approve / Un-approve...) </li><li>Delete an expense </li><li>Edit an expense </li><li>See expense narrative and status changes </li></ul>| <ul><li>**Filter expenses by:**</li><li>Date </li><li>Status </li><li>Type </li><li>Status </li><li>Amount </li><li>Status </li><li>**Search expenses by** </li><li>Title </li><li>Collective </li><li>Submitter (User) </li><li>Expense ID </li></ul> | from the first column|

---



![Screen Capture on 2020-04-01 at 21-44-49](https://user-images.githubusercontent.com/49539954/78208876-b7f31680-7462-11ea-9d5e-3d675767a6a0.gif)

**Comment by piamancini** [comment]
@Memo-Es I can't see the GIF

**Comment by piamancini** [comment]
@Memo-Es can you please update when you can with the application views you demoed on Friday? Thanks!

**Comment by xdamman** [comment]
Since each expense is a conversation, it's important to also show the number of comments and the avatar of the last few people who participated in the conversation.

A common use case is that the host posts a comment to ask for more info. They need to be able to quickly see if someone has responded without having to open that actual expense.

**Comment by xdamman** [comment]
I don't understand the goal of the "global info cards" up there. I don't see why knowing the PayPal/transferwise balance is important information that you need to know outside of any context. I'd only show them whenever you need to select a payout method to pay out an expense (in the exact same way that we show you the different payment methods that you can use when making a donation, each with their available balance if any).

More interesting info for those cards (if you want to keep them), would be an overview of how much work the host has to do right now. That is: 
- how many expenses are ready to pay,
- how many orders are pending (and need to be marked as paid or cancelled), 
- how many applications for hosting are pending
- how many conversations are unanswered on the host page

**Comment by Memo-Es** [comment]
### Update → Expenses and Collectives (Wireframes)
In this screencap is showed the following features and user experience of expense management, application management and Collectives for fiscal host admins:


| Main updates  | 
| ------------- | 
| <ul><li>Showing number of comments and last users</li><li>See application list</li><li>Select an application and its details </li><li>Approve application </li><li>Send a message to the Collective with a public conversation in the Collective's page </li><li>Send a private message to the Collective admins with an email </li><li>Reject an application (Providing a reason with n email to Collective admins </li><li> See list of Collectives hosted </li><li> Possibility to Add funds, set custom fee, contact or un-host the selected Collective</li></ul>| 

---

![HostDashboard_Update](https://user-images.githubusercontent.com/49539954/78742629-313aaf80-7922-11ea-93b5-d9cc42130ea6.gif)

![Screen Capture on 2020-04-07 at 22-49-41](https://user-images.githubusercontent.com/49539954/78742760-8080e000-7922-11ea-8ecd-1ab5caaf08f2.gif)

**Comment by Memo-Es** [comment]
### Update → Collective actions (Wireframes)

In this screencap is showed the following features and user experience of interacting with Collectives through the following actions:

| Add funds | Set custom fees | Contact  | Un-host |
| ------------- | ------------- | ------------- | ------------- |
| ![Add funds](https://user-images.githubusercontent.com/49539954/79290941-fa6d1800-7e92-11ea-8335-d6ecdf29dc4e.png)  <ul><li>Add funds to the Collective</li><li>Set extra fees (Optional)</li> | ![Set custom fees](https://user-images.githubusercontent.com/49539954/79290947-fb9e4500-7e92-11ea-9035-1548c89f63df.png)  <ul> <li>Use global fees (Inherited from settings</li><li>Set custom fee for this Collective only </li> <li>Set a monthly retainer for this Collective (Subscription)</li> | ![Contact](https://user-images.githubusercontent.com/49539954/79290945-fb05ae80-7e92-11ea-8427-afc96ab84458.png)  <ul> <li>Send message to Collective using a public conversation</li><li>Send a private email to Collective admins </li>  |  ![Un-host](https://user-images.githubusercontent.com/49539954/79290949-fc36db80-7e92-11ea-8b03-d65ffb4f0930.png)  <ul> <li>Un-host (Delete) a Collective from your hosted Collectives </li><li>Send a private email to Collective admins explaining why </li>
 
![Screen Capture on 2020-04-14 at 20-53-49 (1)](https://user-images.githubusercontent.com/49539954/79292194-2342dc80-7e96-11ea-8fa7-5c65dd0c272f.gif)

**Comment by flaki** [comment]
These look great! Looking forward to trying the new dashboard!

RE: **Set custom fees**
This *also* looks great.

One potential request -- how about making the "monthly retainer" rather a "charge host fee"?

I think monthly retainers make sense, but I also imagine some might only want to charge a collective e.g. after every event they do (a flat fee), or only if they reached a certain point or whatever else.

The host could pre-agree on a fee, instead of charging a monthly fee, and charge that once the requirements are met. Monthly retainers could be made just by clicking in a [x] make it monthly checkbox right underneath.

So something like:

**Host fees**
- [ ] `Use global host fees`

**Custom**
- [ ] `___% custom host fee`

**One-time host fee**
- `$____ enter host fee` `[Charge]` `[x] make it recurring: monthly`

**Comment by alanna** [comment]
@Memo-Es - The mockups look fantastic! What would be useful to give feedback on at this stage? Can I get access to the prototype you make these gifs from to click through myself? I am available to get involved a bit in this project now if I can help.

@flaki I totally agree! That issue is detailed here: #2843 - seeing how it could be incorporated into these designs is helpful. I also agree that one-time fee is a good option to add.

**Comment by Memo-Es** [comment]
### Update → Expenses UI

Final UI of the expenses section of the host dashboard 

**Note:** There is still an update pending with the payout experience, I will update that soon.
(There can be some modifications to the specific wording in future updates)

---

![Host-dashboard-expenses](https://user-images.githubusercontent.com/49539954/84909999-f79dc780-b07b-11ea-8d24-8b51d9f3aaad.gif)

**Comment by flaki** [comment]
This is looking really good! Can't wait to play with it. :nerd_face:

**Comment by alanna** [comment]
@Memo-Es comments about the Organization settings based on this screenshot:

<img width="241" alt="Screen Shot 2021-04-23 at 12 58 45 PM" src="https://user-images.githubusercontent.com/5498878/115802889-d9d78680-a433-11eb-9021-031145ee3910.png">

Overall, I love the settings menu design. It's just a question of what order and sections things should be in.

`Connected accounts`: doesn't make sense here to me. I think that only has Twitter right? Why is that an Organization setting not Collective setting?

`Your team`: let's stick with `Team` - no need to change stuff so small and have to update docs any everything, and Team is more general.

`Gift cards`: also doesn't seem to make sense here. I know it's here because you've pulled through the settings that are currently seen for Org profiles, but this is a chance to rethink that. `Gift Cards` are something the admin will create, manage, and refer to similar to Expenses or `Virtual Cards`, not like static org info. Actually `Gift cards` is on here twice! Also at the bottom.

`Collective settings`: really doesn't make sense to a Host admin. They don't think of their Host as a Collective and Organization combined, that's just an artefact of how our system evolved. I tried to think of another word for this section heading, but actually given how I think we should remove several of the items in the `about your organization` section, I think what's needed is a rethink of all the sections.

Let's just remove the `about your organization` and `Collective Settings` sub-sections, and simply list out all these things under the overall `Organization settings` header. I still think that on the next level up, `Organization Settings` and `Fiscal Hosting` make sense, but we just don't need these other subsections.

I don't think `Updates` and `Conversations` need to even exist as settings. They are enabled and disabled in the Profile Page settings, and these separate settings don't have any function. Maybe @Betree will comment here saying he's about to introduce settings around Updates to non-contributor subscribers, but in that case, let's have one list item called `Communication` with Updates and Conversations settings under that. Considering how you've merged all Fiscal Host settings into one scrolling page, why not stick with that and further consolidate other areas?

In this context with `contribution tiers` and `manage contributions` right next to each other, it seems easily confusing. I don't know the solution.

Where are `payment methods`, as in managing the credit card this Host Org uses to contribute to other Collectives? Is it under `Manage Contributons`?

Where is `2FA`?

Why get rid of `Advanced`? We have traditionally used that section for a lot more than only `delete organization` and we need a cluster of functions including `archive` and `deactivate as host`. So just `Delete organization` on its own doesn't work. We also often use Advanced to roll out new features or special functions we don't want to reveal in the main settings areas.

**Comment by Memo-Es** [comment]
@alanna, I'm totally up for combining sections and narrowing down the number of options available. Still, according to feedback from @znarf, it is complicated to do that right now, so as far as I understand, we will need to continue having the different sections as we have them now. That's why I think we can at least bundle them together with the dropdown behavior

**Comment by Memo-Es** [comment]
> This is a really old issue, @memo-es is it time to close and open related issues instead? Many of the things proposed here have been deployed. This issue should have been closed when the host dashboard project was finished. 

Yes @piamancini I just added the implementation specs to this other issue #3880 Ben opened some time ago. When that's done we can close the issues referenced there, including this one

**Comment by BenJam** [comment]
Adding this to the roadmap as a 'catch all' for the two issues that we're addressing this sprint: https://github.com/opencollective/opencollective/issues/4300 and https://github.com/opencollective/opencollective/issues/3880

**Comment by Memo-Es** [comment]
@BenJam I think we are ready to close this issue as well wdyt?

**Comment by Betree** [comment]
This is all done. We'll be removing the old dashboard entirely in #4914
